- name: Preseed IDO MySQL package answers
  debconf:
    name: icinga2-ido-mysql
    question: "{{ item.key }}"
    value: "{{ item.value }}"
    vtype: select
  with_dict:
    icinga2-ido-mysql/enable: true
    icinga2-ido-mysql/dbconfig-install: false

- name: Install Icinga, IDO MySQL and Monitoring plugins
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2
    - icinga2-ido-mysql
    - monitoring-plugins

- name: Copy Icinga config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: ido-mysql.conf.j2, dest: /etc/icinga2/features-available/ido-mysql.conf }
    - { src: perfdata.conf.j2, dest: /etc/icinga2/features-available/perfdata.conf }
  notify: reload icinga

- name: Enable Icinga modules
  icinga2_feature:
    name: "{{ item }}"
    state: present
  with_items: "{{ icinga2_modules }}"
  notify: restart icinga

- name: Import Icinga IDO MySQL schema
  mysql_db:
    name: "{{ icinga2_db.name }}"
    state: import
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
  when:
    - db_created.changed
    - synced_config is not defined

- name: Copy configuration files under /etc/icinga2/conf.d
  template:
    src: "{{ item }}.j2"
    dest: "/etc/icinga2/conf.d/{{ item }}"
  notify: reload icinga
  with_items:
    - hosts.conf
    - groups.conf
    - services.conf
    - templates.conf
    - users.conf
    - check-commands.conf
    - http-services.conf
    - notifications.conf

- name: Copy constants.conf
  template:
    src: constants.conf.j2
    dest: /etc/icinga2/constants.conf
  notify: reload icinga

- name: Remove unwanted config files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ icinga2_unwanted_files }}"
  notify: reload icinga

- name: Copy nagios ssh private key
  copy:
    src: "{{ PLAYBOOK_PRIVATE_ROLE_ASSETS_PATH }}nagios_host/nagios"
    dest: /var/lib/nagios/.ssh/id_rsa
    owner: nagios
    group: nagios
    mode: u=rw,g=,o=
  tags: icinga_ssh

- name: Set ssh config
  copy:
    content: |
      Host *
        StrictHostKeyChecking no
    dest: /var/lib/nagios/.ssh/config
    owner: nagios
    group: nagios
    mode: u=rw,g=,o=
  tags: icinga_ssh
